Add service capability to vault snap
canonical/snap-vault pull request #52
Opened 2023-11-02 13:25 UTC by sombrafam

Since vault is mostly used as a server, it makes sense to provide a 'vault server' in the snap.

2023-11-02 13:28 UTC, sombrafam commented
Resolves #48

2023-11-14 17:06 UTC, sombrafam commented
@javacruft can you review this?

2023-11-27 17:02 UTC, javacruft commented on snap/snapcraft.yaml
> +      - network-bind
As the snap is used for cli tooling as well I suspect we'd want to install the snap with this service disabled by default, requiring that it be enabled by the user or tooling being used.

2023-11-27 17:05 UTC, javacruft commented
If we do implement this change we'll need to update the charms to stop installing a systemd service file for the vault daemon.

2024-01-05 17:44 UTC, gruyaume commented
Is this effort still in progress? I see the last commit dates from November 2 2023.

2024-01-08 17:00 UTC, sombrafam commented
Hey @gruyaume, the only thing it's blocking this is the approval/agreement to move forward with this approach. Since your team is the owner of it now, I would like to hear your thoughts about that.

The motivation on our side is that there has been community complaints about the way the snap is packed without the services, we also have a customer with the same request.

2024-01-09 13:36 UTC, gruyaume requested changes

2024-01-09 13:36 UTC, gruyaume commented on snap/snapcraft.yaml
> +version: 1.13.0
Please don't bundle the version update with adding the service, this should be in a different PR.

2024-01-09 13:36 UTC, gruyaume commented on snap/snapcraft.yaml
(not related to this file) we should likely update the README.md to display the new behavior available in this snap now.

2024-01-09 18:08 UTC, gruyaume commented on snap-common/vault.env
Do we need this file? We're sourcing it but there's no env var in it

2024-01-09 18:08 UTC, gruyaume commented on snap/snapcraft.yaml
It may be useful to know that logs will be readable like so:

```
journalctl -b --no-pager -u snap.vault.vaultd.service
```

2024-01-16 19:34 UTC, sombrafam commented on snap/snapcraft.yaml
> +version: 1.13.0
Ok, the last version was bumped by Github Actions. How is that trigged?

2024-01-16 19:55 UTC, gruyaume commented on snap/snapcraft.yaml
> +version: 1.13.0
Yes there were a couple of changes made to the snap including the version, I will likely have to rebase

2024-01-18 06:27 UTC, sombrafam commented on snap/snapcraft.yaml
Agree, it needs better documentation and a description of how it will work.

2024-01-18 06:28 UTC, sombrafam commented on snap-common/vault.env
I'm trying to keep parity with the Vault package service[1] that uses this.

[1] https://github.com/hashicorp/vault/blob/main/.release/linux/package/usr/lib/systemd/system/vault.service

2024-01-18 06:44 UTC, sombrafam commented
Going over the patch again and reconsidering how this should be done, I think that there are some things we need to change: 

1 - I believe we should not try to maintain compatibility with the charm (which I was trying to somewhat achieve) and go for a close parity with what Hashicorp package[1] does, since:
     a - compatibility might not be possible;
     b - the charm should be able to handle differences in the package during it's upgrade;
     c - non-charm usages of the snap should not be affected by charm needs;
2 - we should add automated tests to check if the package is building properly and if the service runs correctly after the installation
___________________
[1] https://github.com/hashicorp/vault/tree/main/.release/linux

2024-01-18 13:39 UTC, gruyaume commented
> Going over the patch again and reconsidering how this should be done, I think that there are some things we need to change:
> 
> 1. I believe we should not try to maintain compatibility with the charm (which I was trying to somewhat achieve) and go for a close parity with what Hashicorp package[1] does, since:
> 
> * compatibility might not be possible;
> * the charm should be able to handle differences in the package during it's upgrade;
> * non-charm usages of the snap should not be affected by charm needs;
> 
> 2. We should add automated tests to check if the package is building properly and if the service runs correctly after the installation.
> 
> [1] https://github.com/hashicorp/vault/tree/main/.release/linux

We're in the process of writing [a completely new version of the Machine charm](https://github.com/canonical/vault-operator) for Vault so please don't base your decisions on trying to make the snap compatible with the existing charm.

2024-01-22 19:26 UTC, gruyaume commented
Closing this PR as this feature as been added in PR #67

2024-01-22 19:26 UTC, closed without merging